### ISSUE TITLE
Publish a null safe version of the package

### ISSUE THREAD

**Issue by SteveAlexander** [Huulivoide/format_bytes#2]
There's a pull request ready at https://github.com/Huulivoide/format_bytes/pull/1

**Comment by SteveAlexander** [comment]
Hi @Huulivoide 

I’m using this package, and finding it great to use. I wonder if you have time to look at my null-safety PR?

Thanks

**Comment by Huulivoide** [comment]
I pulled in the PR ages ago, but forgot to publish the package to pub.dev 🫠 sorry for that.
New version is finally up 🙈
