### ISSUE TITLE
Publish with intl 0.17

### ISSUE THREAD

**Issue by tmpfs** [Huulivoide/format_bytes#3]
I tried to install but it conflicted with a dependency on an old version of `intl` so I needed to use a git dependency.

Can you publish the version with the updated `intl` dependency please?

**Comment by Huulivoide** [comment]
Deps have been updated. But this is probably of no help to you anymore. Sorry for reacting to this so slowly.

**Comment by tmpfs** [comment]
Thanks @Huulivoide, actually good that I no longer need to rely on the fork! 👍
